version: '3'

services:
  web:
    build: 
        context: ./docker
        network: host
    ports:
      - "8989:80"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    volumes:
          - './src/:/code'
          - './models/:/models'